#!/usr/local/bin/perl -w

$repl = shift;

while(<>) {
	$line = $_;
	if(/\.word	inst(..)_SYM\+(.)(.*)$/) {
		if($repl eq "c") {
			print "\t0x$2,	/* $1 */ $3\n";
		} else {
			print "\t.word\tinst$1" . "_$repl" . "+$2$3\n";
		}
	} elsif (/\.block.*$/) {
		if($repl eq "c") {
			print "\n";
		} else {
			print $line;
		}
	} else {
		print $line;
	}
}
#	if(/^inst(..)_SYM		(.*)$/) {
#		print "OPCODE($1)	/* $2 */\n";
#	} else if(/^(
